### PR TITLE
Channel reference in the ClosedChannel

### LINKED ISSUE #73: Interaction between ChannelError and Select
Hello!

I have built an abstraction that internally use `Channels`. I am now designing the exception handling for it. When I read from a single channel everything is clear, I can translate `ChannelError` to whatever I need and provide context of my abstraction.

Where I have a problem is when I use `Select#select`. In this case, when an error occurs I do not know from which channel it originates and I have to go through all of them to check whether I have the correct one. 

Would it be possible to either expose the channel on `ChannelClosed` or allow some sort of metadata to be attached to a channel that would then be accessible on `ChannelClosed`? Or is there a better way of doing such a thing?

I am willing to work on it myself if you deem such a feature desirable.

Thanks

### PR DESCRIPTION
**Pull request by Blef666**
Closes #73

### CODE REVIEW

File: channels/src/main/java/com/softwaremill/jox/Select.java [hunk 1]
```diff
@@ -72,16 +72,21 @@ public static <U> U select(SelectClause<? extends U>... clauses) throws Interrup
      * <p>
      * If no clauses are given, returns {@link ChannelDone}.
      *
-     * @param clauses The clauses, from which one will be selected. Not {@code null}.
+     * @param clauses The clauses, from which one will be selected. Must not be empty or {@code null}.
+     *                Can't contain {@code null} values.
```
Comment (adamw) [inline channels/src/main/java/com/softwaremill/jox/Select.java:76]: "must not be empty or null. Can't contain null values" - don't we repeat ourselves here? :)

**Review by adamw — APPROVED** [review]
Looks good, thanks! :)

File: channels/src/main/java/com/softwaremill/jox/Select.java (hunk 1 above)
Comment (Blef666) [reply channels/src/main/java/com/softwaremill/jox/Select.java:76]: No, because it's not only about the list being null, but also its elements. Although I can rephrase it.

**Comment by adamw** [comment]
-> merge conflicts, sorry :)
plus, a failed build, but seems unrelated; I'll add a timeout so that we can investigate
